name: Scrape Upcoming Releases

on:
  schedule:
    - cron: "0 * * * *" # run every hour
  workflow_dispatch:    # allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run scraper and save JSON
        run: python scrape.py > releases.json
      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add releases.json last_hash.txt
          git diff --cached --quiet || git commit -m "Update releases.json"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

