name: Update Upcoming Releases

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:       # manual trigger

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper and save JSON
        run: python scrape.py > releases.json

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add releases.json
          if git diff --cached --quiet; then
            echo "No changes detected, skipping commit & deploy."
            exit 0
          fi
          git commit -m "Update releases.json"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/vortexit07/Hits.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact (just releases.json)
        uses: actions/upload-pages-artifact@v3
        with:
          path: releases.json

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
