name: Update Upcoming Releases

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:       # manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper and save JSON
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        run: python scrape.py > releases.json

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add releases.json
          if git diff --cached --quiet; then
            echo "No changes detected, exiting."
            exit 0
          fi
          git commit -m "Update releases.json"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/vortexit07/Hits.git HEAD:main --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
